export const formattedJobData = {
    'id': 'Id',
    'form_creation_date': 'Creation Date',
    'template_choices': 'Template Choice',
    'job_stage': 'Job Stage',
    'choice_of_user': 'Choice of User',
    'job_posting_website': 'Job Website',
    'position_title': 'Position Title',
    'company': 'Company',
    'city': 'City',
    'link': 'Job Link',
    'recruiter': 'Recruiter',
    'description': 'Description',
    'pre_bullet_point_paragraph_one': 'Pre Paragraph One',
    'pre_bullet_point_paragraph_two': 'Pre Paragraph Two',
    'top_skills': 'Top Skills',
    'bullet_point_one': 'Bullet Point One',
    'bullet_point_two': 'Bullet Point Two',
    'bullet_point_three': 'Bullet Point Three',
    'bullet_point_four': 'Bullet Point Four',
    'bullet_point_five': 'Bullet Point Five',
    'bullet_point_six': 'Bullet Point Six',
    'bullet_point_seven': 'Bullet Point Seven',
    'bullet_point_eight': 'Bullet Point Eight',
    'post_bullet_point_paragraph_one': 'Post Paragraph One',
    'post_bullet_point_paragraph_two': 'Post Paragraph Two',
    'modified_date': 'Modified Date',
    'created_date': 'Created Date',
    'belongs_to_user': 'Belongs To User ID',
}

export const formattedUserData = {
    "first_name": "First Name",
    "middle_name":"Middle Name",
    "last_name":"Last Name",
    "preferred_name":"Preferred Name",
    "phone_number":"Phone Number Name",
    "linkedin":"Linkedin",
    "github":"Github",
    "portfolio_website":"Portfolio Website",
    "street_address":"Stree Address",
    "city_address":"City Address",
    "state_address":"State Address",
    "zip_code":"Zip Code",

}