# Generated by Django 3.1.4 on 2020-12-11 20:40

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_choices', models.CharField(blank='False', choices=[('Standard Job Template', 'Standard Job Template'), ('Triplebyte (message-version)', 'Triplebyte (message-version)'), ('non-technical-cover-letter', 'Non-technical Cover Letter'), ('cover-letter-4', 'Template 4'), ('cover-letter-5', 'Template 5')], max_length=200)),
                ('job_stage', models.CharField(blank='False', choices=[('Initial', 'Initial'), ('Active', 'Active'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('No Response', 'No Response')], max_length=100)),
                ('job_posting_website', models.CharField(blank=True, default='', max_length=200, verbose_name='Job Posting Website')),
                ('position_title', models.CharField(blank=True, default='', max_length=200, verbose_name='Position Title')),
                ('city', models.CharField(blank=True, default='', max_length=200)),
                ('pre_bullet_point_paragraph_one', models.TextField(blank=True, default='')),
                ('pre_bullet_point_paragraph_two', models.TextField(blank=True, default='')),
                ('top_skills', models.TextField(blank=True, default='')),
                ('bullet_point_one', models.TextField(blank=True, default='')),
                ('bullet_point_two', models.TextField(blank=True, default='')),
                ('bullet_point_three', models.TextField(blank=True, default='')),
                ('bullet_point_four', models.TextField(blank=True, default='')),
                ('bullet_point_five', models.TextField(blank=True, default='')),
                ('bullet_point_six', models.TextField(blank=True, default='')),
                ('bullet_point_seven', models.TextField(blank=True, default='')),
                ('bullet_point_eight', models.TextField(blank=True, default='')),
                ('post_bullet_point_paragraph_one', models.TextField(blank=True, default='')),
                ('post_bullet_point_paragraph_two', models.TextField(blank=True, default='')),
                ('modified_date', models.DateField(auto_now=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date', '-modified_date'],
                'get_latest_by': ['-created_date', 'modified_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('preferred_name', models.CharField(blank=True, max_length=200)),
                ('phone_number', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('portfolio_website', models.URLField(blank=True, null=True)),
                ('street_address', models.CharField(blank=True, max_length=200)),
                ('city_address', models.CharField(blank=True, max_length=200)),
                ('state_address', models.CharField(blank=True, max_length=200)),
                ('zip_code', models.CharField(blank=True, max_length=200)),
                ('modified_date', models.DateField(auto_now=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('default_info', models.OneToOneField(blank=True, default=61, on_delete=django.db.models.deletion.CASCADE, to='coverLetters.defaultinfo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-modified_date'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_creation_date', models.CharField(blank=True, default='December 11th, 2020', max_length=100)),
                ('template_choices', models.CharField(blank='False', choices=[('Standard Job Template', 'Standard Job Template'), ('Triplebyte (message-version)', 'Triplebyte (message-version)'), ('non-technical-cover-letter', 'Non-technical Cover Letter'), ('cover-letter-4', 'Template 4'), ('cover-letter-5', 'Template 5')], default='non-technical-cover-letter', max_length=100)),
                ('job_stage', models.CharField(blank='False', choices=[('Initial', 'Initial'), ('Active', 'Active'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('No Response', 'No Response')], default='Initial', max_length=100)),
                ('job_posting_website', models.CharField(default='LinkedIn', max_length=200, verbose_name='Job Posting Website')),
                ('position_title', models.CharField(max_length=200, verbose_name='Position Title')),
                ('company', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('link', models.CharField(max_length=1000)),
                ('recruiter', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pre_bullet_point_paragraph_one', models.TextField(blank=True)),
                ('pre_bullet_point_paragraph_two', models.TextField(blank=True)),
                ('top_skills', models.TextField(blank=True)),
                ('bullet_point_one', models.TextField(blank=True)),
                ('bullet_point_two', models.TextField(blank=True)),
                ('bullet_point_three', models.TextField(blank=True)),
                ('bullet_point_four', models.TextField(blank=True)),
                ('bullet_point_five', models.TextField(blank=True)),
                ('bullet_point_six', models.TextField(blank=True)),
                ('bullet_point_seven', models.TextField(blank=True)),
                ('bullet_point_eight', models.TextField(blank=True)),
                ('post_bullet_point_paragraph_one', models.TextField(blank=True)),
                ('post_bullet_point_paragraph_two', models.TextField(blank=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('belongs_to_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date', '-modified_date', '-position_title'],
                'get_latest_by': ['-created_date', 'modified_date'],
                'unique_together': {('link', 'position_title', 'belongs_to_user')},
            },
        ),
    ]
