# Generated by Django 3.0.3 on 2020-08-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('job_title', models.CharField(max_length=200)),
                ('job_link', models.CharField(max_length=200, null=True)),
                ('top_skills', models.TextField(null=True)),
                ('extra_line_one', models.TextField(null=True)),
                ('extra_line_two', models.TextField(null=True)),
                ('extra_line_three', models.TextField(null=True)),
                ('extra_line_four', models.TextField(null=True)),
                ('extra_line_five', models.TextField(null=True)),
                ('extra_line_six', models.TextField(null=True)),
                ('extra_line_seven', models.TextField(null=True)),
                ('extra_line_eight', models.TextField(null=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
