# Generated by Django 3.1 on 2020-11-29 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0002_auto_20201129_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='choice_of_user',
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
