# Generated by Django 3.0.3 on 2020-08-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0002_auto_20200817_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_title',
            new_name='title',
        ),
    ]
