# Generated by Django 3.1.4 on 2020-12-11 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0003_auto_20201211_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_info',
            field=models.OneToOneField(blank=True, default=81, on_delete=django.db.models.deletion.CASCADE, to='coverLetters.defaultinfo'),
        ),
    ]
