# Generated by Django 3.1 on 2020-12-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0003_auto_20201129_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='form_creation_date',
            field=models.CharField(blank=True, default='December 01th, 2020', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('link', 'template_choices', 'position_title', 'belongs_to_user')},
        ),
    ]
