# Generated by Django 3.0.3 on 2020-08-17 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0003_auto_20200817_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company_name',
            new_name='company',
        ),
    ]
