# Generated by Django 3.0.3 on 2020-08-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0004_auto_20200817_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter_title', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('job_title', models.CharField(max_length=200)),
                ('cover_letter', models.TextField()),
                ('job_id', models.ManyToManyField(to='coverLetters.Job')),
            ],
        ),
    ]
