# Generated by Django 3.1.4 on 2020-12-11 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0004_auto_20201211_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_info',
            field=models.OneToOneField(blank=True, default=83, on_delete=django.db.models.deletion.DO_NOTHING, to='coverLetters.defaultinfo'),
        ),
    ]
