# Generated by Django 3.0.3 on 2020-08-17 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0005_coverletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='cover_letter_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='coverletter',
            name='job_id',
        ),
        migrations.AddField(
            model_name='coverletter',
            name='job_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coverLetters.Job'),
            preserve_default=False,
        ),
    ]
