# Generated by Django 3.1.4 on 2020-12-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0005_auto_20201201_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='form_creation_date',
            field=models.CharField(blank=True, default='December 03th, 2020', max_length=100),
        ),
    ]
