# Generated by Django 3.0.3 on 2020-08-17 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0006_auto_20200817_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='job_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coverLetters.Job'),
        ),
    ]
