# Generated by Django 3.0.3 on 2020-08-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0006_auto_20200818_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='portfolio_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
