# Generated by Django 3.1.4 on 2020-12-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0006_auto_20201203_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='form_creation_date',
            field=models.CharField(blank=True, default='December 04th, 2020', max_length=100),
        ),
    ]
