# Generated by Django 3.1.4 on 2020-12-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0007_auto_20201204_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='form_creation_date',
            field=models.CharField(blank=True, default='December 05th, 2020', max_length=100),
        ),
    ]
