# Generated by Django 3.0.3 on 2020-08-19 16:38

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0008_auto_20200819_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
