# Generated by Django 3.1.4 on 2020-12-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0008_auto_20201211_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='form_creation_date',
            field=models.CharField(blank=True, default='December 13th, 2020', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_posting_website',
            field=models.CharField(max_length=200, verbose_name='Job Posting Website'),
        ),
    ]
