# Generated by Django 3.1.4 on 2020-12-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0008_auto_20201205_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_posting_website',
        ),
        migrations.AlterField(
            model_name='job',
            name='form_creation_date',
            field=models.CharField(blank=True, default='December 08th, 2020', max_length=100),
        ),
    ]
