# Generated by Django 3.1.4 on 2020-12-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0009_auto_20201208_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_posting_website',
            field=models.CharField(default='Google', max_length=200, verbose_name='Job Posting Website'),
        ),
        migrations.AlterField(
            model_name='job',
            name='form_creation_date',
            field=models.CharField(blank=True, default='December 09th, 2020', max_length=100),
        ),
    ]
