# Generated by Django 3.1.4 on 2020-12-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0009_auto_20201213_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_posting_website',
            field=models.CharField(blank=True, max_length=200, verbose_name='Job Posting Website'),
        ),
    ]
