# Generated by Django 3.1.4 on 2020-12-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0010_auto_20201209_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='form_creation_date',
            field=models.CharField(blank=True, default='December 10th, 2020', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='template_choices',
            field=models.CharField(blank='False', choices=[('Standard Job Template', 'Standard Job Template'), ('Triplebyte (message-version)', 'Triplebyte (message-version)'), ('non-technical-cover-letter', 'Non-technical Cover Letter'), ('cover-letter-4', 'Template 4'), ('cover-letter-5', 'Template 5')], default='non-technical-cover-letter', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='top_skills',
            field=models.TextField(blank=True),
        ),
    ]
