# Generated by Django 3.0.3 on 2020-08-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0010_auto_20200819_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='bullet_point_eight',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='bullet_point_five',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='bullet_point_four',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='bullet_point_one',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='bullet_point_seven',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='bullet_point_six',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='bullet_point_three',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='bullet_point_two',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='post_bullet_point_paragraph_one',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='post_bullet_point_paragraph_two',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='pre_bullet_point_paragraph_one',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='pre_bullet_point_paragraph_two',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='recruiter',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='top_skills',
            field=models.TextField(blank=True, default='Dynamic and accomplished Software Engineer with experience and expertise in'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='city_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='middle_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='portfolio_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='state_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='street_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='zip_code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
