# Generated by Django 3.1.4 on 2020-12-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0011_auto_20201210_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_creation_date', models.CharField(blank=True, default='December 10th, 2020', max_length=100)),
                ('template_choices', models.CharField(blank='False', choices=[('Standard Job Template', 'Standard Job Template'), ('Triplebyte (message-version)', 'Triplebyte (message-version)'), ('non-technical-cover-letter', 'Non-technical Cover Letter'), ('cover-letter-4', 'Template 4'), ('cover-letter-5', 'Template 5')], default='non-technical-cover-letter', max_length=100)),
                ('job_stage', models.CharField(blank='False', choices=[('Initial', 'Initial'), ('Active', 'Active'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('No Response', 'No Response')], default='Initial', max_length=100)),
                ('job_posting_website', models.CharField(max_length=200, verbose_name='Job Posting Website')),
                ('position_title', models.CharField(max_length=200, verbose_name='Position Title')),
                ('city', models.CharField(blank=True, max_length=200)),
                ('pre_bullet_point_paragraph_one', models.TextField(blank=True)),
                ('pre_bullet_point_paragraph_two', models.TextField(blank=True)),
                ('top_skills', models.TextField(blank=True)),
                ('bullet_point_one', models.TextField(blank=True)),
                ('bullet_point_two', models.TextField(blank=True)),
                ('bullet_point_three', models.TextField(blank=True)),
                ('bullet_point_four', models.TextField(blank=True)),
                ('bullet_point_five', models.TextField(blank=True)),
                ('bullet_point_six', models.TextField(blank=True)),
                ('bullet_point_seven', models.TextField(blank=True)),
                ('bullet_point_eight', models.TextField(blank=True)),
                ('post_bullet_point_paragraph_one', models.TextField(blank=True)),
                ('post_bullet_point_paragraph_two', models.TextField(blank=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date', '-modified_date'],
                'get_latest_by': ['-created_date', 'modified_date'],
            },
        ),
        migrations.AlterField(
            model_name='job',
            name='job_posting_website',
            field=models.CharField(default='LinkedIn', max_length=200, verbose_name='Job Posting Website'),
        ),
    ]
