# Generated by Django 3.0.3 on 2020-08-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0012_job_template_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='template_choices',
            field=models.CharField(choices=[('Template 1', 'cover-letter-1'), ('Template 2', 'cover-letter-2'), ('Template 3', 'cover-letter-3'), ('Template 4', 'cover-letter-4'), ('Template 5', 'cover-letter-5')], default=1, max_length=20),
        ),
    ]
