# Generated by Django 3.1.4 on 2020-12-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0012_auto_20201210_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultinfo',
            name='bullet_point_eight',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='defaultinfo',
            name='bullet_point_five',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='defaultinfo',
            name='bullet_point_four',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='defaultinfo',
            name='bullet_point_one',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='defaultinfo',
            name='bullet_point_seven',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='defaultinfo',
            name='bullet_point_six',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='defaultinfo',
            name='bullet_point_three',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='defaultinfo',
            name='bullet_point_two',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='defaultinfo',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='defaultinfo',
            name='job_posting_website',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Job Posting Website'),
        ),
        migrations.AlterField(
            model_name='defaultinfo',
            name='position_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Position Title'),
        ),
        migrations.AlterField(
            model_name='defaultinfo',
            name='post_bullet_point_paragraph_one',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='defaultinfo',
            name='post_bullet_point_paragraph_two',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='defaultinfo',
            name='pre_bullet_point_paragraph_one',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='defaultinfo',
            name='pre_bullet_point_paragraph_two',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='defaultinfo',
            name='top_skills',
            field=models.TextField(blank=True, default=''),
        ),
    ]
