# Generated by Django 3.1.4 on 2020-12-10 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0013_auto_20201210_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultinfo',
            name='form_creation_date',
        ),
    ]
