# Generated by Django 3.1 on 2020-09-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0014_auto_20200820_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='users',
            field=models.ManyToManyField(to='coverLetters.UserDetail'),
        ),
    ]
