# Generated by Django 3.1.4 on 2020-12-10 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0014_remove_defaultinfo_form_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coverLetters.defaultinfo'),
            preserve_default=False,
        ),
    ]
