# Generated by Django 3.1 on 2020-09-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0015_auto_20200903_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='choice_of_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coverLetters.userdetail'),
        ),
    ]
