# Generated by Django 3.1.4 on 2020-12-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0018_auto_20201210_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='form_creation_date',
            field=models.CharField(blank=True, default='December 11th, 2020', max_length=100),
        ),
    ]
