# Generated by Django 3.1.4 on 2020-12-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0019_auto_20201211_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultinfo',
            name='template_choices',
            field=models.CharField(blank='False', choices=[('Standard Job Template', 'Standard Job Template'), ('Triplebyte (message-version)', 'Triplebyte (message-version)'), ('non-technical-cover-letter', 'Non-technical Cover Letter'), ('cover-letter-4', 'Template 4'), ('cover-letter-5', 'Template 5')], max_length=200),
        ),
    ]
