# Generated by Django 3.1.4 on 2020-12-11 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0020_auto_20201211_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_info',
            field=models.OneToOneField(blank=True, default=4, null=True, on_delete=django.db.models.deletion.CASCADE, to='coverLetters.defaultinfo'),
        ),
    ]
