# Generated by Django 3.1 on 2020-09-09 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0028_auto_20200909_0704'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('link', 'template_choices', 'position_title')},
        ),
    ]
