# Generated by Django 3.1 on 2020-09-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0031_auto_20200912_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
    ]
