# Generated by Django 3.1 on 2020-09-15 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0032_auto_20200912_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='form_creation_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
