# Generated by Django 3.1 on 2020-09-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0039_auto_20200915_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='form_creation_date',
            field=models.CharField(blank=True, default='September 15th, 2020', max_length=100),
        ),
    ]
