# Generated by Django 3.1 on 2020-09-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0040_auto_20200915_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-modified_date']},
        ),
        migrations.AlterModelOptions(
            name='userdetail',
            options={'ordering': ['-modified_date']},
        ),
        migrations.AlterField(
            model_name='job',
            name='form_creation_date',
            field=models.CharField(blank=True, default='September 16th, 2020', max_length=100),
        ),
    ]
