# Generated by Django 3.1 on 2020-09-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0045_auto_20200916_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='form_creation_date',
            field=models.CharField(blank=True, default='September 28th, 2020', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_posting_website',
            field=models.CharField(max_length=200, verbose_name='Job Posting Website'),
        ),
        migrations.AlterField(
            model_name='job',
            name='position_title',
            field=models.CharField(max_length=200, verbose_name='Position Title'),
        ),
    ]
