# Generated by Django 3.1 on 2020-09-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0045_auto_20200916_2226'),
        ('coverLetters', '0045_auto_20200916_2229'),
    ]

    operations = [
    ]
