# Generated by Django 3.1 on 2020-10-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0042_auto_20200916_2114 2'),
        ('coverLetters', '0046_auto_20200928_2024'),
    ]

    operations = [
    ]
