# Generated by Django 3.1 on 2020-11-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0048_auto_20201025_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_stage',
            field=models.CharField(blank='False', choices=[('Initial', 'Initial'), ('Active', 'Active'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Initial', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='form_creation_date',
            field=models.CharField(blank=True, default='November 04th, 2020', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='template_choices',
            field=models.CharField(blank='False', choices=[('Standard Job Template', 'Standard Job Template'), ('Triplebyte (message-version)', 'Triplebyte (message-version)'), ('non-technical-cover-letter', 'Non-technical Cover Letter'), ('cover-letter-4', 'Template 4'), ('cover-letter-5', 'Template 5')], default='Standard Job Template', max_length=100),
        ),
    ]
