# Generated by Django 3.1 on 2020-10-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0048_auto_20201025_2106'),
        ('coverLetters', '0046_merge_20200923_1640'),
    ]

    operations = [
    ]
