# Generated by Django 3.1 on 2020-11-05 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0050_auto_20201104_2238'),
        ('coverLetters', '0049_merge_20201028_1812'),
    ]

    operations = [
    ]
