# Generated by Django 3.0.3 on 2020-08-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='recruiter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
