# Generated by Django 3.0.3 on 2020-08-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0005_auto_20200818_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='top_skills',
            field=models.TextField(blank=True, default='Dynamic and accomplished Software Engineer with experience and expertise in', null=True),
        ),
    ]
