# Generated by Django 3.0.3 on 2020-08-19 20:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0011_auto_20200819_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='template_choices',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Template 1', 'cover-letter-1'), ('Template 2', 'cover-letter-2'), ('Template 3', 'cover-letter-3'), ('Template 4', 'cover-letter-4'), ('Template 5', 'cover-letter-5')], default='cover-letter-1', max_length=54),
            preserve_default=False,
        ),
    ]
