# Generated by Django 3.1 on 2020-09-03 17:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0014_auto_20200820_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='choice_of_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='coverLetters.userdetail'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetail',
            name='modified_date',
            field=models.DateField(auto_now=True),
        ),
    ]
