# Generated by Django 3.1 on 2020-09-04 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0016_auto_20200904_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='choice_of_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='coverLetters.userdetail'),
        ),
    ]
