# Generated by Django 3.1 on 2020-09-06 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0020_job_choice_of_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='choice_of_user',
        ),
        migrations.AddField(
            model_name='job',
            name='choice_of_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coverLetters.userdetail'),
        ),
    ]
