# Generated by Django 3.1 on 2020-09-06 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0021_auto_20200906_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='position_title',
        ),
    ]
