# Generated by Django 3.1 on 2020-09-06 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0023_auto_20200906_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='choice_of_user',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='coverLetters.userdetail'),
        ),
        migrations.AlterField(
            model_name='job',
            name='template_choices',
            field=models.CharField(choices=[('Standard Job Template', 'cover-letter-1'), ('Triplebyte (message-version)', 'cover-letter-2'), ('Template 3', 'cover-letter-3'), ('Template 4', 'cover-letter-4'), ('Template 5', 'cover-letter-5')], default='Template 1', max_length=100),
        ),
    ]
