# Generated by Django 3.1 on 2020-09-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0026_auto_20200908_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='template_choices',
            field=models.CharField(blank='False', choices=[('Standard Job Template', 'Standard Job Template'), ('Triplebyte (message-version)', 'Triplebyte (message-version)'), ('Non-technical Cover Letter', 'non-technical-cover-letter'), ('Template 4', 'cover-letter-4'), ('Template 5', 'cover-letter-5')], default='Standard Job Template', max_length=100),
        ),
    ]
