# Generated by Django 3.1 on 2020-09-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0027_auto_20200909_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('link', 'template_choices')},
        ),
    ]
