# Generated by Django 3.1 on 2020-09-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0033_job_form_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='form_creation_date',
        ),
    ]
