# Generated by Django 3.1 on 2020-09-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0036_auto_20200915_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='form_creation_date',
            field=models.DateField(default=models.DateField(auto_now_add=True)),
        ),
    ]
