# Generated by Django 3.1 on 2020-09-16 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0041_auto_20200916_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-modified_date', 'modified_date', 'id']},
        ),
    ]
