# Generated by Django 3.1 on 2020-09-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0042_auto_20200916_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_date', 'modified_date', 'id']},
        ),
    ]
