# Generated by Django 3.1 on 2020-11-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0049_auto_20201104_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_stage',
            field=models.CharField(blank='False', choices=[('Initial', 'Initial'), ('Active', 'Active'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Rejected', max_length=100),
        ),
    ]
