# Generated by Django 3.1 on 2020-11-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0051_auto_20201117_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='form_creation_date',
            field=models.CharField(blank=True, default='November 22th, 2020', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_stage',
            field=models.CharField(blank='False', choices=[('Initial', 'Initial'), ('Active', 'Active'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('No Response', 'No Response')], default='Initial', max_length=100),
        ),
    ]
