# Generated by Django 3.1 on 2020-11-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0052_auto_20201122_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='form_creation_date',
            field=models.CharField(blank=True, default='November 26th, 2020', max_length=100),
        ),
    ]
