# Generated by Django 3.1 on 2020-11-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverLetters', '0053_auto_20201126_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='form_creation_date',
            field=models.CharField(blank=True, default='November 27th, 2020', max_length=100),
        ),
    ]
